version: '3'

services:
  bkind.web:
    image: bkind.web
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
       - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRESS_USER: postgres
      POSTGRES_PASSWORD: Bkind123!
      POSTGRES_DB: bkind
    ports:
      - '5430:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    
